# .github/actions/tflint/action.yaml
name: 'Terraform Linter'
description: 'Run TFLint on Terraform code'

inputs:
  tflint-ver:
    description: 'TFLint version to use'
    required: false
    default: "v0.52.0"

  use-cache:
    description: 'Enable TFLint plugin caching (true|false)'
    required: false
    default: "true"

  tflint-format:
    description: 'TFLint output format (default, json, compact, checkstyle)'
    required: false
    default: "compact"

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache TFLint plugins
      if: ${{ inputs.use-cache == 'true' }}
      uses: actions/cache@v3
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: ${{ inputs.tflint-ver }}

    - name: Show TFLint version
      run: tflint --version
      shell: bash

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash

    - name: Run TFLint and save output
      id: tflint
      run: |
        tflint -f ${{ inputs.tflint-format }} > tflint.out || true
        echo "################# tflint.out ###################"
        cat tflint.out
        echo "################################################"
        echo '### TFLint Results (`${{ inputs.tflint-format }}` format)' >> "$GITHUB_STEP_SUMMARY"
        echo '```' >> "$GITHUB_STEP_SUMMARY"
        cat tflint.out >> "$GITHUB_STEP_SUMMARY"
        echo '```' >> "$GITHUB_STEP_SUMMARY"
        test ! -s tflint.out
      shell: bash
